const {test,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'revizionedit-test-'));process.env.ORDER_DATA_DIR=tmp;process.env.SQUARE_LOCATION_ID='test-location';
const {server,makeSquareRequest,paymentVerified,cleanPhotos}=require('../server.cjs');
const M=require('../public/order-model');
after(()=>fs.rmSync(tmp,{recursive:true,force:true}));
test('payment request includes server prices and design reference',()=>{const o={lines:[{product:'basic',quantity:1}],addons:{},event:{date:'2027-01-20',name:'Maya',theme:'Pink'},photos:[],contact:{email:'maya@example.com'},fulfillment:'shipping',address:{line1:'123 Main',city:'Springfield',state:'IL',zip:'62704'}};const q=M.quote(o,new Date('2026-09-25'));const r=makeSquareRequest('test-order','test-token',o,q,{percentage:0,shippingTaxable:false,rushTaxable:false});assert.equal(r.order.reference_id,'test-order');assert.equal(r.order.line_items[0].base_price_money.amount,6500);assert.equal(r.order.line_items[1].base_price_money.amount,2000);assert.equal(r.checkout_options.ask_for_shipping_address,false);assert.equal(r.pre_populated_data.buyer_email,'maya@example.com');});
test('payment confirmation requires matching amount, order, location and currency',()=>{const order={square_order:'order-a',amount:6500};const p={status:'COMPLETED',order_id:'order-a',amount_money:{amount:6500,currency:'USD'},location_id:'test-location'};assert.equal(paymentVerified(p,order),true);assert.equal(paymentVerified({...p,status:'PENDING'},order),false);assert.equal(paymentVerified({...p,amount_money:{amount:100,currency:'USD'}},order),false);assert.equal(paymentVerified({...p,order_id:'different'},order),false);});
test('rejects renamed non-image uploads',()=>assert.throws(()=>cleanPhotos([{name:'photo.png',data:'data:image/png;base64,'+Buffer.from('<script>fake photo</script>').toString('base64')}])));
test('preview API blocks checkout and private file access',async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const base='http://127.0.0.1:'+server.address().port;const config=await fetch(base+'/api/config');assert.equal((await config.json()).checkoutReady,false);const pay=await fetch(base+'/api/checkout',{method:'POST',body:'{}'});assert.equal(pay.status,503);const file=await fetch(base+'/private/orders.sqlite');assert.equal(file.status,404);const hook=await fetch(base+'/api/square-webhook',{method:'POST',body:'{}'});assert.equal(hook.status,403);const status=await fetch(base+'/api/order-status?token=wrong');assert.equal(status.status,404);}finally{await new Promise(r=>server.close(r));}});
